import { CertificationsSchema, type Certification } from './schema';

const VERIFIED = '2026-05-15';

const rawCertifications = [
  {
    id: 1,
    slug: 'google-it-support',
    provider: 'Google',
    name: 'Google IT Support Professional Certificate',
    shortTitle: 'Google IT Support',
    description:
      'Entry-level program covering troubleshooting, networking, operating systems, and customer support. Coursera offers full financial aid that waives the fee.',
    link: 'https://www.coursera.org/professional-certificates/google-it-support',
    skills: ['IT Support', 'Troubleshooting', 'Networking', 'Linux', 'Customer Service'],
    tracks: ['it-support', 'foundations'],
    estimatedHours: 120,
    recommendedOrder: 1,
    careerFit: ['IT support specialist', 'Help desk technician', 'Desktop support technician'],
    outcomes: [
      'Troubleshoot common hardware, software, and network issues',
      'Use Linux command-line tools for file and process tasks',
      'Explain DNS, DHCP, TCP/IP, and basic routing in support tickets',
      'Document customer issues with clear next actions',
    ],
    prerequisites: ['Basic computer use'],
    bestFor: ['First-time IT learners', 'Career changers targeting help desk roles'],
    notFor: ['People who already administer enterprise networks'],
    assessmentFormat: 'Quizzes, labs, and graded assignments across a multi-course certificate',
    credentialType: 'certificate',
    nextSteps: ['azure-fundamentals', 'aws-cloud-practitioner-essentials'],
    freeAccess: {
      type: 'financial-aid',
      summary: 'The full Professional Certificate can be unlocked through Coursera financial aid.',
      steps: [
        'Open the certificate page on Coursera while signed out',
        'Click "Enroll for free" and choose "Financial aid available"',
        'Submit the aid application; plan for about 15 minutes',
        'Wait for approval before enrolling in the certificate track',
      ],
      caveat: 'Coursera often defaults to a free trial that becomes a paid subscription. Apply for aid before enrolling.',
      proofUrl: 'https://www.coursera.org/about/scholarship-application',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '6 months',
    lastUpdated: VERIFIED,
  },
  {
    id: 2,
    slug: 'google-data-analytics',
    provider: 'Google',
    name: 'Google Data Analytics Professional Certificate',
    shortTitle: 'Google Data Analytics',
    description:
      'Hands-on path through spreadsheets, SQL, R, and Tableau with case-study capstones. Coursera financial aid is available for the full certificate.',
    link: 'https://www.coursera.org/professional-certificates/google-data-analytics',
    skills: ['Data Analysis', 'SQL', 'R', 'Tableau', 'Spreadsheets'],
    tracks: ['data'],
    estimatedHours: 120,
    recommendedOrder: 2,
    careerFit: ['Junior data analyst', 'Reporting analyst', 'Operations analyst'],
    outcomes: [
      'Clean tabular data with spreadsheets and SQL',
      'Write SQL queries that filter, join, and aggregate datasets',
      'Build basic dashboards and charts for stakeholder questions',
      'Use R to prepare and visualize data for a capstone case study',
    ],
    prerequisites: ['Comfort with spreadsheets'],
    bestFor: ['Beginners who want a structured analytics path', 'Operations workers moving into reporting'],
    notFor: ['Data engineers looking for production pipeline training'],
    assessmentFormat: 'Course quizzes, labs, and portfolio-style case studies',
    credentialType: 'certificate',
    nextSteps: ['ibm-data-science', 'google-ai-essentials'],
    freeAccess: {
      type: 'financial-aid',
      summary: 'Coursera financial aid can cover the certificate path instead of a monthly subscription.',
      steps: [
        'Open the certificate page on Coursera',
        'Use the "Financial aid available" link near enrollment',
        'Apply before starting the paid trial',
        'After approval, complete each course in the certificate sequence',
      ],
      caveat: 'Aid may be handled per course in the series. Starting a trial first can create a paid charge.',
      proofUrl: 'https://www.coursera.org/about/scholarship-application',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '6 months',
    lastUpdated: VERIFIED,
  },
  {
    id: 3,
    slug: 'azure-fundamentals',
    provider: 'Microsoft',
    name: 'Microsoft Certified: Azure Fundamentals (AZ-900)',
    shortTitle: 'Azure Fundamentals',
    description:
      'Foundational Azure exam covering cloud concepts, core services, security, pricing, and governance. The full Learn path is free; exam vouchers are offered through Microsoft events.',
    link: 'https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/',
    skills: ['Cloud', 'Azure', 'Identity', 'Governance', 'Pricing'],
    tracks: ['cloud', 'foundations'],
    estimatedHours: 12,
    recommendedOrder: 3,
    careerFit: ['Cloud support associate', 'Junior cloud administrator', 'Technical sales specialist'],
    outcomes: [
      'Compare IaaS, PaaS, and SaaS choices in Azure',
      'Explain Azure identity, access, and governance basics',
      'Estimate simple workloads with Azure pricing tools',
      'Describe core compute, storage, and networking services',
    ],
    prerequisites: ['Basic cloud vocabulary helps but is not required'],
    bestFor: ['Beginners choosing a first cloud exam', 'Support or sales staff who need Azure fluency'],
    notFor: ['Engineers who already deploy production Azure workloads'],
    assessmentFormat: 'Proctored Microsoft certification exam, usually multiple choice and scenario questions',
    credentialType: 'certification',
    nextSteps: ['azure-ai-fundamentals', 'power-platform-fundamentals'],
    freeAccess: {
      type: 'free-learning-paid-exam',
      summary: 'Microsoft Learn modules are free; the AZ-900 exam is paid unless you have a valid voucher.',
      steps: [
        'Study the AZ-900 learning path on Microsoft Learn for free',
        'Check Microsoft events for voucher or discount offers before scheduling',
        'Schedule the exam only after a voucher is available if you need the exam at no cost',
      ],
      caveat: 'The learning is free, but the certification is not free without a current voucher or employer program.',
      proofUrl: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/az-900/',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '10-12 hours',
    lastUpdated: VERIFIED,
  },
  {
    id: 4,
    slug: 'azure-ai-fundamentals',
    provider: 'Microsoft',
    name: 'Microsoft Certified: Azure AI Fundamentals (AI-900)',
    shortTitle: 'Azure AI Fundamentals',
    description:
      'Free Microsoft Learn path covering machine learning, computer vision, NLP, and Azure AI services. Pairs well with the AI Engineer career trajectory.',
    link: 'https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/',
    skills: ['AI', 'Machine Learning', 'Azure AI', 'Computer Vision', 'NLP'],
    tracks: ['ai', 'cloud', 'foundations'],
    estimatedHours: 10,
    recommendedOrder: 4,
    careerFit: ['AI product analyst', 'Cloud support associate', 'Junior AI builder'],
    outcomes: [
      'Identify when to use machine learning, vision, language, and generative AI services',
      'Describe responsible AI principles in Microsoft cloud projects',
      'Map common AI workloads to Azure AI services',
      'Read basic evaluation terms for classification and regression models',
    ],
    prerequisites: ['Basic cloud vocabulary helps but is not required'],
    bestFor: ['Non-specialists who need AI vocabulary', 'Learners preparing for Azure AI services'],
    notFor: ['Machine learning engineers who need model-training depth'],
    assessmentFormat: 'Proctored Microsoft certification exam, usually multiple choice and scenario questions',
    credentialType: 'certification',
    nextSteps: ['google-ai-essentials', 'openai-academy'],
    freeAccess: {
      type: 'free-learning-paid-exam',
      summary: 'The Microsoft Learn study path is free; the AI-900 exam requires payment unless a voucher applies.',
      steps: [
        'Complete the AI-900 learning path on Microsoft Learn',
        'Use Microsoft practice assessment resources at no cost',
        'Watch Microsoft events and student or employer programs for exam voucher access',
      ],
      caveat: 'Completing Learn modules does not award the Microsoft certification. The exam is the paid step.',
      proofUrl: 'https://learn.microsoft.com/en-us/credentials/certifications/azure-ai-fundamentals/',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '10 hours',
    lastUpdated: VERIFIED,
  },
  {
    id: 5,
    slug: 'anthropic-courses',
    provider: 'Anthropic',
    name: 'Anthropic Courses: Prompt Engineering & Claude API',
    shortTitle: 'Anthropic Courses',
    description:
      'Free interactive courses on prompt engineering, tool use, real-world applications, and the Claude API hosted on GitHub by Anthropic.',
    link: 'https://github.com/anthropics/courses',
    skills: ['Prompt Engineering', 'Claude API', 'Tool Use', 'AI Safety'],
    tracks: ['ai'],
    estimatedHours: 8,
    recommendedOrder: 5,
    careerFit: ['AI application developer', 'Prompt engineer', 'Technical product builder'],
    outcomes: [
      'Write prompts with clear task, context, and output constraints',
      'Test prompt variants against real model outputs',
      'Use tool-calling examples to connect model output to application actions',
      'Apply basic safety checks before shipping Claude-powered workflows',
    ],
    prerequisites: ['Basic Python or notebook comfort'],
    bestFor: ['Developers learning Claude workflows', 'AI builders who prefer hands-on notebooks'],
    notFor: ['Learners who need a formal third-party certificate'],
    assessmentFormat: 'Self-check notebooks and exercises in GitHub',
    credentialType: 'course-completion',
    nextSteps: ['deeplearning-ai-chatgpt-prompt-engineering', 'openai-academy'],
    freeAccess: {
      type: 'free-course-paid-certificate',
      summary: 'The course materials are free on GitHub; there is no formal certificate path listed in the repo.',
      steps: [
        'Open the Anthropic courses repository on GitHub',
        'Choose the prompt engineering or Claude API course folder',
        'Run the notebooks locally or in a hosted notebook environment',
      ],
      caveat: 'Treat this as free training, not a formal credential for hiring screens.',
      proofUrl: 'https://github.com/anthropics/courses',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Intermediate',
    duration: 'Self-paced',
    lastUpdated: VERIFIED,
  },
  {
    id: 6,
    slug: 'openai-academy',
    provider: 'OpenAI',
    name: 'OpenAI Academy',
    shortTitle: 'OpenAI Academy',
    description:
      'OpenAI Academy delivers free courses and live sessions on ChatGPT, the OpenAI API, and applied AI for professionals, educators, and developers.',
    link: 'https://academy.openai.com/',
    skills: ['ChatGPT', 'OpenAI API', 'Prompt Engineering', 'Generative AI'],
    tracks: ['ai'],
    estimatedHours: 6,
    recommendedOrder: 6,
    careerFit: ['AI product builder', 'Educator using AI', 'Developer using OpenAI APIs'],
    outcomes: [
      'Use ChatGPT workflows for practical work and learning tasks',
      'Identify when an OpenAI API workflow needs retrieval, tools, or structured output',
      'Apply basic AI safety and privacy checks in everyday usage',
    ],
    prerequisites: ['Basic familiarity with ChatGPT'],
    bestFor: ['Professionals adopting AI tools', 'Developers and educators who want first-party OpenAI guidance'],
    notFor: ['Learners seeking a single proctored certification exam'],
    assessmentFormat: 'Varies by course or live session',
    credentialType: 'course-completion',
    nextSteps: ['deeplearning-ai-chatgpt-prompt-engineering', 'google-ai-essentials'],
    freeAccess: {
      type: 'free-course-paid-certificate',
      summary: 'OpenAI describes Academy as a free public learning hub with courses and sessions.',
      steps: [
        'Open OpenAI Academy',
        'Create or sign in to an Academy account',
        'Browse courses or upcoming sessions and enroll at no cost',
      ],
      caveat: 'Course availability and completion records can vary by session; do not assume every item awards a shareable credential.',
      proofUrl: 'https://help.openai.com/en/articles/8313434-are-there-any-resources-for-educators-to-learn-more-about-ai',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Intermediate',
    duration: 'Self-paced',
    lastUpdated: VERIFIED,
  },
  {
    id: 7,
    slug: 'aws-cloud-practitioner-essentials',
    provider: 'AWS',
    name: 'AWS Cloud Practitioner Essentials',
    shortTitle: 'AWS Essentials',
    description:
      'AWS Skill Builder digital course covering core AWS services, pricing, security, and architectural concepts. Free with an AWS Builder account.',
    link: 'https://skillbuilder.aws/exam-prep/cloud-practitioner',
    skills: ['AWS', 'Cloud', 'IAM', 'EC2', 'S3'],
    tracks: ['cloud', 'foundations'],
    estimatedHours: 6,
    recommendedOrder: 3,
    careerFit: ['Cloud support associate', 'Junior AWS administrator', 'Technical account associate'],
    outcomes: [
      'Explain shared responsibility for common AWS workloads',
      'Compare core AWS compute, storage, database, and networking services',
      'Configure IAM users and roles for least-privilege access',
      'Identify billing, support, and pricing concepts for AWS accounts',
    ],
    prerequisites: ['Basic cloud vocabulary helps but is not required'],
    bestFor: ['New AWS learners', 'IT support staff moving into cloud support'],
    notFor: ['Learners who need the official CLF-C02 exam credential for free'],
    assessmentFormat: 'Course knowledge checks and optional paid certification exam',
    credentialType: 'badge',
    nextSteps: ['aws-cloud-quest-cloud-practitioner', 'azure-fundamentals'],
    freeAccess: {
      type: 'free-badge',
      summary: 'AWS Skill Builder offers free digital training and selected digital badges with an AWS Builder ID.',
      steps: [
        'Create a free AWS Builder ID',
        'Open the Cloud Practitioner learning resources in AWS Skill Builder',
        'Complete the listed course activities and any badge-eligible assessment',
      ],
      caveat: 'The badge is not the AWS Certified Cloud Practitioner exam. The CLF-C02 exam is paid.',
      proofUrl: 'https://aws.amazon.com/training/badges/',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '6 hours',
    lastUpdated: VERIFIED,
  },
  {
    id: 8,
    slug: 'ibm-ai-fundamentals',
    provider: 'IBM',
    name: 'IBM SkillsBuild: Artificial Intelligence Fundamentals',
    shortTitle: 'IBM AI Fundamentals',
    description:
      'Free IBM SkillsBuild learning plan covering AI concepts, machine learning, neural networks, ethics, and a hands-on capstone with a digital credential.',
    link: 'https://skillsbuild.org/students/course-catalog/artificial-intelligence',
    skills: ['AI', 'Machine Learning', 'Neural Networks', 'AI Ethics'],
    tracks: ['ai', 'foundations'],
    estimatedHours: 20,
    recommendedOrder: 4,
    careerFit: ['AI learner', 'Business analyst using AI', 'Junior automation builder'],
    outcomes: [
      'Explain machine learning, neural networks, and generative AI in plain language',
      'Identify risks around bias, privacy, and responsible AI use',
      'Complete a simple AI capstone using guided tools',
    ],
    prerequisites: ['No technical background required'],
    bestFor: ['New AI learners who want a credential', 'Students building a first AI portfolio entry'],
    notFor: ['Developers looking for API-heavy AI engineering practice'],
    assessmentFormat: 'Learning plan activities and IBM digital credential requirements',
    credentialType: 'badge',
    nextSteps: ['google-ai-essentials', 'azure-ai-fundamentals'],
    freeAccess: {
      type: 'free-badge',
      summary: 'IBM SkillsBuild offers free courses and digital credentials, including AI Fundamentals.',
      steps: [
        'Create a free IBM SkillsBuild account',
        'Enroll in the Artificial Intelligence Fundamentals learning plan',
        'Complete the required activities to claim the IBM digital credential',
      ],
      caveat: 'The credential is an IBM SkillsBuild digital credential, not a vendor-neutral certification exam.',
      proofUrl: 'https://skillsbuild.org/students/digital-credentials',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '20 hours',
    lastUpdated: VERIFIED,
  },
  {
    id: 9,
    slug: 'freecodecamp-responsive-web-design',
    provider: 'freeCodeCamp',
    name: 'Responsive Web Design Certification',
    shortTitle: 'Responsive Web Design',
    description:
      'Project-based certification covering HTML, CSS, accessibility, and responsive layout. Five required projects unlock the free verified credential.',
    link: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
    skills: ['HTML', 'CSS', 'Accessibility', 'Flexbox', 'Grid'],
    tracks: ['web'],
    estimatedHours: 300,
    recommendedOrder: 1,
    careerFit: ['Junior front-end developer', 'Web content specialist', 'Accessibility-minded designer'],
    outcomes: [
      'Build semantic HTML pages with accessible form and media patterns',
      'Use CSS Flexbox and Grid for responsive layouts',
      'Pass freeCodeCamp project tests for five certification projects',
    ],
    prerequisites: ['No coding background required'],
    bestFor: ['Beginners learning front-end basics', 'Learners who want project-based validation'],
    notFor: ['React developers looking for framework depth'],
    assessmentFormat: 'Five required projects checked by freeCodeCamp tests',
    credentialType: 'certificate',
    nextSteps: ['freecodecamp-javascript-algorithms'],
    freeAccess: {
      type: 'free-certificate',
      summary: 'freeCodeCamp curriculum and certifications are free after you complete the required projects.',
      steps: [
        'Create a free freeCodeCamp account',
        'Complete the Responsive Web Design lessons',
        'Submit and pass the five certification projects',
        'Claim the free certification from your profile',
      ],
      caveat: 'The credential depends on passing projects, not just watching lessons.',
      proofUrl: 'https://www.freecodecamp.org/learn/2022/responsive-web-design/',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '300 hours',
    lastUpdated: VERIFIED,
  },
  {
    id: 10,
    slug: 'freecodecamp-javascript-algorithms',
    provider: 'freeCodeCamp',
    name: 'JavaScript Algorithms and Data Structures Certification',
    shortTitle: 'JavaScript Algorithms',
    description:
      'Long-form curriculum on JavaScript fundamentals, ES6, regex, debugging, OOP, functional programming, and algorithm projects.',
    link: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/',
    skills: ['JavaScript', 'Algorithms', 'Data Structures', 'OOP', 'Functional Programming'],
    tracks: ['web'],
    estimatedHours: 300,
    recommendedOrder: 2,
    careerFit: ['Junior JavaScript developer', 'Front-end developer', 'Technical support engineer'],
    outcomes: [
      'Write JavaScript functions using arrays, objects, loops, and modules',
      'Use regular expressions for text validation and parsing',
      'Solve algorithm projects that pass automated tests',
      'Apply basic OOP and functional programming patterns',
    ],
    prerequisites: ['Basic HTML and CSS experience'],
    bestFor: ['Learners moving from HTML/CSS to programming', 'Front-end beginners who need JavaScript practice'],
    notFor: ['Developers looking for TypeScript or React architecture'],
    assessmentFormat: 'Required coding projects checked by freeCodeCamp tests',
    credentialType: 'certificate',
    nextSteps: ['harvard-cs50'],
    freeAccess: {
      type: 'free-certificate',
      summary: 'The curriculum and JavaScript certification are free through freeCodeCamp.',
      steps: [
        'Create a free freeCodeCamp account',
        'Complete the JavaScript curriculum sections',
        'Pass the required certification projects',
        'Claim the certification from your freeCodeCamp profile',
      ],
      caveat: 'Expect a long practice path. The certificate is free, but it is not a short course.',
      proofUrl: 'https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Intermediate',
    duration: '300 hours',
    lastUpdated: VERIFIED,
  },
  {
    id: 11,
    slug: 'hubspot-inbound-marketing',
    provider: 'HubSpot',
    name: 'HubSpot Academy: Inbound Marketing Certification',
    shortTitle: 'Inbound Marketing',
    description:
      'HubSpot Academy free certification on inbound methodology, content strategy, buyer personas, and conversational marketing.',
    link: 'https://academy.hubspot.com/courses/inbound-marketing',
    skills: ['Inbound Marketing', 'Content Strategy', 'SEO', 'Buyer Personas'],
    tracks: ['marketing'],
    estimatedHours: 4,
    recommendedOrder: 1,
    careerFit: ['Marketing coordinator', 'Content marketer', 'Small business owner'],
    outcomes: [
      'Define buyer personas and map content to lifecycle stages',
      'Plan inbound campaigns around search, content, and conversion goals',
      'Use HubSpot terminology for leads, contacts, and buyer journeys',
    ],
    prerequisites: ['Basic marketing vocabulary helps but is not required'],
    bestFor: ['New marketers', 'Founders handling their own content strategy'],
    notFor: ['Advanced growth marketers needing analytics depth'],
    assessmentFormat: 'HubSpot Academy lessons and certification exam',
    credentialType: 'certificate',
    nextSteps: ['google-ai-essentials'],
    freeAccess: {
      type: 'free-certificate',
      summary: 'HubSpot Academy offers the inbound marketing course and certification for free.',
      steps: [
        'Create a free HubSpot Academy account',
        'Enroll in the Inbound Marketing Certification course',
        'Complete the lessons and pass the certification exam',
      ],
      caveat: 'You may see HubSpot product prompts, but the Academy certification course itself is free.',
      proofUrl: 'https://academy.hubspot.com/courses/inbound-marketing',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '4 hours',
    lastUpdated: VERIFIED,
  },
  {
    id: 12,
    slug: 'harvard-cs50',
    provider: 'HarvardX',
    name: 'CS50: Introduction to Computer Science',
    shortTitle: 'Harvard CS50',
    description:
      'Harvard\'s flagship CS course on edX. Free to audit, with a paid certificate option. Covers C, Python, SQL, web development, and algorithms.',
    link: 'https://www.edx.org/learn/computer-science/harvard-university-cs50-s-introduction-to-computer-science',
    skills: ['C', 'Python', 'SQL', 'Algorithms', 'Web Development'],
    tracks: ['web', 'foundations', 'data'],
    estimatedHours: 120,
    recommendedOrder: 2,
    careerFit: ['Software engineering learner', 'Technical founder', 'Computer science student'],
    outcomes: [
      'Write small programs in C and Python using variables, loops, and functions',
      'Use SQL to query relational data in course projects',
      'Explain basic algorithms, memory, and web request concepts',
      'Build a final project that combines course topics',
    ],
    prerequisites: ['Comfort with self-paced academic coursework'],
    bestFor: ['Learners who want a rigorous CS foundation', 'Developers filling gaps in fundamentals'],
    notFor: ['Learners who need a free verified edX certificate'],
    assessmentFormat: 'Problem sets and final project; verified edX certificate requires payment',
    credentialType: 'course-completion',
    nextSteps: ['freecodecamp-javascript-algorithms', 'ibm-data-science'],
    freeAccess: {
      type: 'free-course-paid-certificate',
      summary: 'The edX audit path gives free course access; the verified edX certificate is paid.',
      steps: [
        'Open the CS50 edX course page',
        'Choose the free audit option when enrolling',
        'Use the course materials without buying the verified certificate',
      ],
      caveat: 'Audit access does not include the paid verified edX certificate.',
      proofUrl: 'https://support.edx.org/hc/en-us/articles/360013426573-What-are-the-differences-between-audit-free-and-verified-paid-courses',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '12 weeks',
    lastUpdated: VERIFIED,
  },
  {
    id: 13,
    slug: 'ibm-data-science',
    provider: 'IBM',
    name: 'IBM Data Science Professional Certificate',
    shortTitle: 'IBM Data Science',
    description:
      'Intermediate Coursera certificate covering Python, SQL, data analysis, visualization, machine learning basics, and a capstone project.',
    link: 'https://www.coursera.org/professional-certificates/ibm-data-science',
    skills: ['Python', 'SQL', 'Data Science', 'Machine Learning', 'Data Visualization'],
    tracks: ['data', 'ai'],
    estimatedHours: 160,
    recommendedOrder: 5,
    careerFit: ['Junior data scientist', 'Data analyst', 'Machine learning learner'],
    outcomes: [
      'Use Python notebooks to clean, analyze, and visualize datasets',
      'Query relational data with SQL for data science tasks',
      'Train and evaluate introductory machine learning models',
      'Complete a data science capstone with a public artifact',
    ],
    prerequisites: ['Comfort with spreadsheets or basic programming helps'],
    bestFor: ['Analytics learners ready for Python', 'Google Data Analytics graduates moving deeper'],
    notFor: ['Experienced data scientists needing advanced MLOps'],
    assessmentFormat: 'Coursera quizzes, labs, peer review, and capstone project',
    credentialType: 'certificate',
    nextSteps: ['google-ai-essentials', 'azure-ai-fundamentals'],
    freeAccess: {
      type: 'financial-aid',
      summary: 'Coursera lists financial aid for the IBM Data Science Professional Certificate.',
      steps: [
        'Open the IBM Data Science certificate page on Coursera',
        'Use the financial aid link before starting the paid trial',
        'Apply for aid for the courses in the certificate sequence',
        'Enroll after aid is approved and finish the required projects',
      ],
      caveat: 'Professional certificates can require aid per course. Check each course before assuming the whole path is covered.',
      proofUrl: 'https://www.coursera.org/professional-certificates/ibm-data-science',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Intermediate',
    duration: '5 months',
    lastUpdated: VERIFIED,
  },
  {
    id: 14,
    slug: 'power-platform-fundamentals',
    provider: 'Microsoft',
    name: 'Microsoft Certified: Power Platform Fundamentals (PL-900)',
    shortTitle: 'Power Platform',
    description:
      'Microsoft Learn path covering Power Apps, Power Automate, Power BI, Copilot Studio, Dataverse, and business automation concepts.',
    link: 'https://learn.microsoft.com/en-us/credentials/certifications/power-platform-fundamentals/',
    skills: ['Power Platform', 'Power Apps', 'Power Automate', 'Dataverse', 'Power BI'],
    tracks: ['foundations', 'data'],
    estimatedHours: 10,
    recommendedOrder: 4,
    careerFit: ['Business analyst', 'Citizen developer', 'Operations automation specialist'],
    outcomes: [
      'Identify when to use Power Apps, Power Automate, Power BI, and Dataverse',
      'Describe low-code automation patterns for business processes',
      'Explain Power Platform governance and connector basics',
    ],
    prerequisites: ['Basic business process knowledge'],
    bestFor: ['Business users moving into low-code tools', 'Analysts who need Microsoft platform fluency'],
    notFor: ['Developers seeking advanced Power Platform administration'],
    assessmentFormat: 'Proctored Microsoft certification exam after free Learn preparation',
    credentialType: 'certification',
    nextSteps: ['azure-fundamentals', 'google-data-analytics'],
    freeAccess: {
      type: 'free-learning-paid-exam',
      summary: 'The Microsoft Learn preparation path is free; earning PL-900 requires the paid exam unless a voucher applies.',
      steps: [
        'Study the PL-900 learning paths on Microsoft Learn',
        'Use the free practice assessment if available in your region',
        'Look for employer, student, or event vouchers before scheduling the exam',
      ],
      caveat: 'Completing the free learning path does not award the Microsoft certification.',
      proofUrl: 'https://learn.microsoft.com/en-us/credentials/certifications/exams/pl-900/',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '10 hours',
    lastUpdated: VERIFIED,
  },
  {
    id: 15,
    slug: 'aws-cloud-quest-cloud-practitioner',
    provider: 'AWS',
    name: 'AWS Cloud Quest: Cloud Practitioner',
    shortTitle: 'AWS Cloud Quest',
    description:
      'Game-based AWS Skill Builder training where learners solve cloud scenarios and can earn an AWS digital badge.',
    link: 'https://explore.skillbuilder.aws/learn/course/external/view/elearning/11458/aws-cloud-quest-cloud-practitioner',
    skills: ['AWS', 'Cloud', 'Architecture', 'IAM', 'Networking'],
    tracks: ['cloud', 'foundations'],
    estimatedHours: 12,
    recommendedOrder: 4,
    careerFit: ['Cloud support associate', 'Junior solutions architect learner', 'AWS beginner'],
    outcomes: [
      'Match AWS services to practical cloud scenarios',
      'Practice basic architecture choices in guided cloud tasks',
      'Use AWS vocabulary for identity, networking, storage, and compute',
    ],
    prerequisites: ['Basic cloud vocabulary helps but is not required'],
    bestFor: ['Hands-on learners who prefer scenario practice', 'AWS beginners preparing before a paid exam'],
    notFor: ['Learners who need a proctored AWS certification for free'],
    assessmentFormat: 'Interactive challenges and AWS digital badge criteria',
    credentialType: 'badge',
    nextSteps: ['aws-cloud-practitioner-essentials', 'azure-fundamentals'],
    freeAccess: {
      type: 'free-badge',
      summary: 'AWS lists Cloud Quest among Skill Builder training badges available through its digital badge program.',
      steps: [
        'Create a free AWS Builder ID',
        'Open AWS Cloud Quest: Cloud Practitioner in Skill Builder',
        'Complete the required Cloud Quest activities',
        'Claim the AWS digital badge after Skill Builder records the criteria as complete',
      ],
      caveat: 'The Cloud Quest badge is not the paid AWS Certified Cloud Practitioner exam credential.',
      proofUrl: 'https://aws.amazon.com/training/badges/',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '12 hours',
    lastUpdated: VERIFIED,
  },
  {
    id: 16,
    slug: 'google-cybersecurity',
    provider: 'Google',
    name: 'Google Cybersecurity Professional Certificate',
    shortTitle: 'Google Cybersecurity',
    description:
      'Beginner Coursera certificate covering security foundations, Linux, SQL, Python, SIEM tools, and incident response practice.',
    link: 'https://www.coursera.org/professional-certificates/google-cybersecurity',
    skills: ['Cybersecurity', 'SIEM', 'Linux', 'SQL', 'Python'],
    tracks: ['security', 'it-support'],
    estimatedHours: 160,
    recommendedOrder: 4,
    careerFit: ['Cybersecurity analyst', 'SOC analyst trainee', 'IT support specialist moving into security'],
    outcomes: [
      'Identify common threats, vulnerabilities, and controls',
      'Use Linux, SQL, and Python for beginner security tasks',
      'Interpret SIEM alerts and document incident response steps',
      'Apply security frameworks to entry-level analyst scenarios',
    ],
    prerequisites: ['No security background required'],
    bestFor: ['Beginners targeting security analyst roles', 'IT support learners adding security skills'],
    notFor: ['Security engineers seeking advanced cloud security architecture'],
    assessmentFormat: 'Coursera quizzes, labs, and portfolio activities across the certificate',
    credentialType: 'certificate',
    nextSteps: ['google-it-support', 'azure-fundamentals'],
    freeAccess: {
      type: 'financial-aid',
      summary: 'Coursera lists financial aid for the Google Cybersecurity Professional Certificate.',
      steps: [
        'Open the certificate page on Coursera',
        'Choose the financial aid option before starting a paid subscription',
        'Apply for aid for the course sequence',
        'Enroll after approval and complete the required labs and assessments',
      ],
      caveat: 'Coursera advertises a 7-day trial and monthly pricing. Aid is the no-cost route, not the trial.',
      proofUrl: 'https://www.coursera.org/professional-certificates/google-cybersecurity',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '6 months',
    lastUpdated: VERIFIED,
  },
  {
    id: 17,
    slug: 'deeplearning-ai-chatgpt-prompt-engineering',
    provider: 'DeepLearning.AI',
    name: 'ChatGPT Prompt Engineering for Developers',
    shortTitle: 'ChatGPT Prompting',
    description:
      'Short developer course by DeepLearning.AI and OpenAI covering prompt patterns, iterative testing, summarization, extraction, transformation, and chatbots.',
    link: 'https://www.deeplearning.ai/courses/chatgpt-prompt-eng/',
    skills: ['Prompt Engineering', 'OpenAI API', 'Python', 'LLMs', 'Chatbots'],
    tracks: ['ai', 'web'],
    estimatedHours: 2,
    recommendedOrder: 5,
    careerFit: ['AI application developer', 'Prompt engineer', 'Full-stack developer using LLMs'],
    outcomes: [
      'Write prompts for summarization, extraction, transformation, and expansion tasks',
      'Iterate on prompts by testing model output against expected behavior',
      'Build a simple chatbot flow in a notebook environment',
    ],
    prerequisites: ['Basic Python familiarity'],
    bestFor: ['Developers adding LLM features', 'Prompting learners who want code examples'],
    notFor: ['Learners who need a free completion certificate'],
    assessmentFormat: 'Video lessons, code examples, and a graded assignment for paid Pro access',
    credentialType: 'course-completion',
    nextSteps: ['openai-academy', 'anthropic-courses'],
    freeAccess: {
      type: 'free-course-paid-certificate',
      summary: 'The course page lists free course access during the learning platform beta; accomplishments are tied to Pro.',
      steps: [
        'Open the DeepLearning.AI course page',
        'Choose the free learning option if it is available',
        'Complete the videos and code examples without upgrading',
      ],
      caveat: 'The free path is course access. The accomplishment or graded credential may require Pro.',
      proofUrl: 'https://www.deeplearning.ai/courses/chatgpt-prompt-eng/',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Intermediate',
    duration: '1.5 hours',
    lastUpdated: VERIFIED,
  },
  {
    id: 18,
    slug: 'google-ai-essentials',
    provider: 'Google',
    name: 'Google AI Essentials',
    shortTitle: 'Google AI Essentials',
    description:
      'Beginner Coursera program on using generative AI tools for brainstorming, writing, analysis, task automation, and responsible use.',
    link: 'https://www.coursera.org/learn/google-ai-essentials',
    skills: ['Generative AI', 'Prompting', 'Productivity', 'Responsible AI'],
    tracks: ['ai', 'foundations'],
    estimatedHours: 10,
    recommendedOrder: 2,
    careerFit: ['Knowledge worker using AI', 'Marketing coordinator', 'Operations analyst'],
    outcomes: [
      'Write specific prompts for research, writing, planning, and analysis tasks',
      'Choose when to verify, revise, or reject AI-generated output',
      'Use AI tools to speed up repetitive workplace tasks',
    ],
    prerequisites: ['Basic comfort using web apps'],
    bestFor: ['Beginners learning practical AI use', 'Non-developers who need prompt basics'],
    notFor: ['Developers looking for API integration practice'],
    assessmentFormat: 'Coursera course activities and certificate assessments',
    credentialType: 'certificate',
    nextSteps: ['openai-academy', 'deeplearning-ai-chatgpt-prompt-engineering'],
    freeAccess: {
      type: 'financial-aid',
      summary: 'Google states that Coursera financial aid can give recipients full access to the course content and assignments.',
      steps: [
        'Open the Google AI Essentials page on Coursera',
        'Use the financial aid link near enrollment',
        'Submit the Coursera aid application before paying',
        'Enroll after approval to complete the certificate requirements',
      ],
      caveat: 'Coursera may show paid subscription or trial options first. Use financial aid for the no-cost route.',
      proofUrl: 'https://www.coursera.org/learn/google-ai-essentials',
      verifiedAt: VERIFIED,
    },
    verifiedFreeAt: VERIFIED,
    level: 'Beginner',
    duration: '10 hours',
    lastUpdated: VERIFIED,
  },
];

function validateCertifications(input: unknown): Certification[] {
  const result = CertificationsSchema.safeParse(input);
  if (result.success) return result.data;

  const firstIssue = result.error.issues[0];
  const path = firstIssue?.path?.join('.') ?? '(unknown path)';
  // Surface the offending cert id (when known) to make data drift trivial to locate.
  const certIndex = typeof firstIssue?.path?.[0] === 'number' ? firstIssue.path[0] : null;
  const certId =
    certIndex !== null && Array.isArray(input) && input[certIndex] && typeof input[certIndex] === 'object'
      ? (input[certIndex] as { id?: unknown }).id
      : undefined;

  const idHint = certId !== undefined ? ` (cert id=${String(certId)})` : '';
  throw new Error(
    `Invalid certifications data${idHint} at ${path}: ${firstIssue?.message ?? 'unknown validation error'}`,
  );
}

export const Certifications: Certification[] = validateCertifications(rawCertifications);
